### ISSUE TITLE
open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by SUA778** [zxj963577494/ionic-AutoUpdateApp#4]
body: null
code: 1
exception: "/storage/emulated/0/Download/eduDemo.apk: open failed: EACCES (Permission denied)"
http_status: 200
source: "http://192.168.1.114:8080/default/edu/uploadfile/apk/demo.apk"
target: "file:///storage/emulated/0/Download/eduDemo.apk"

**Comment by zxj963577494** [comment]
@yue-yue 权限问题吧！搜索一下看看！
